### ISSUE TITLE
Question about adding matlab.less for extra syntax support

### ISSUE THREAD

**Issue by KCErb** [JamesRitchie/language-matlab#9]
Hi all,

I've been using the language-matlab package for some time now. Thanks for porting this!

Today I learned that I can customize my favorite syntax theme in a languages/matlab.less file. The one I just created looks like this:

```less
.source.matlab {
  .keyword {
    &.mathematics {
      color: black;
      font-weight: bold;
    }
    &.desktop {
      color: rgb(214, 56, 56);
      font-weight: bold;
    }
  }
  .storage {
    &.control {
      color: rgb(214, 56, 56);
      font-weight: bold;
    }
  }
  .support {
    &.graphics {
      color: rgb(214, 56, 56);
      font-weight: bold;
    }
  }
}
```

You might see that I just copied my bold-red style from `keyword.desktop.matlab` over to `storage.control.matlab` and `support.graphics.matlab`.

I'm wondering how to DRY this kind of thing up. For example, in your `grammars/m.cson` I see a few groupings like [`all_matlab_keywords'](https://github.com/JamesRitchie/language-matlab/blob/master/grammars/m.cson#L136).

Does anyone know how I can select for that in a `less` file like the one above? I would hope I could do something like

```less
.source.matlab {
  .all_matlab_keywords {
    color: red;
  }
}
```

(but I can't).

Cheers,

KC
